export const OPTIONS = [
  {
    value: "Francia",
    selected: false,
    common: true,
  },
  {
    value: "Svizzera",
    common: true,
    selected: true
  },
  { value: "Cina", common: true },
  { value: "Germania", common: true },
  { value: "Regno Unito", common: true },
  { value: "Stati Uniti", selected: false, common: true },
  { value: "Afghanistan" },
  { value: "Albania" },
  { value: "Algeria" },
  { value: "Croazia" },
  { value: "Grecia" },
  { value: "Grecia" },
  { value: "Grecia", common: false },
  { value: "Grecia" },
  { value: "Grecia" },
  { value: "Grecia" },
  { value: "Egitto", common: false },
  { value: "Grecia" },
  { value: "Azerbaijan", common: false },
  { value: "Germania" },
  { value: "Regno Unito" },
  { value: "Stati Uniti" },
  { value: "Afghanistan", common: false },
  { value: "Albania", common: false },
  { value: "Algeria", common: false },
  { value: "Croazia" },
  { value: "Grecia" },
  { value: "Grecia" },
  { value: "Grecia" },
  { value: "Grecia" },
  { value: "Grecia" },
  { value: "Grecia" },
  { value: "Grecia" },
  { value: "Grecia" },
  { value: "Romania", common: false },
  { value: "Bulgaria", common: false },
];
